/**
 * Downloads the Sketchfab BYD Seal 5 model (CC BY-NC-SA) into public/models/seal5/
 *
 * 1. Create a free API token: https://sketchfab.com/settings/password
 * 2. Run:
 *    $env:SKETCHFAB_API_TOKEN="your_token"; npm run download:seal5
 */
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join, dirname, relative, extname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'

const UID = 'c3bdefa332384e95a9fd249d0abb25c3'
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = join(ROOT, 'public', 'models', 'seal5')
const ZIP_PATH = join(ROOT, 'public', 'models', 'seal5-download.zip')
const URL_MODULE = join(ROOT, 'src', 'three', 'modelUrl.ts')

const token = process.env.SKETCHFAB_API_TOKEN
if (!token) {
  console.error(`
Missing SKETCHFAB_API_TOKEN.

Get one at: https://sketchfab.com/settings/password  (API section)
Then run:

  $env:SKETCHFAB_API_TOKEN="YOUR_TOKEN"
  npm run download:seal5

Model license: CC BY-NC-SA — credit Ddiaz Design, non-commercial only.
https://sketchfab.com/3d-models/2025-byd-seal-5-dm-i-chazor-king-destroyer-05-${UID}
`)
  process.exit(1)
}

function findModelFile(dir) {
  const entries = readdirSync(dir, { withFileTypes: true })
  for (const entry of entries) {
    const p = join(dir, entry.name)
    if (entry.isFile()) {
      const ext = extname(entry.name).toLowerCase()
      if (ext === '.gltf' || ext === '.glb') return p
    } else if (entry.isDirectory()) {
      const nested = findModelFile(p)
      if (nested) return nested
    }
  }
  return null
}

async function main() {
  mkdirSync(dirname(ZIP_PATH), { recursive: true })
  if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true, force: true })
  mkdirSync(OUT_DIR, { recursive: true })

  console.log('Requesting Sketchfab download URL…')
  const metaRes = await fetch(`https://api.sketchfab.com/v3/models/${UID}/download`, {
    headers: { Authorization: `Token ${token}` },
  })
  if (!metaRes.ok) {
    const body = await metaRes.text()
    throw new Error(`Sketchfab download API failed (${metaRes.status}): ${body}`)
  }
  const meta = await metaRes.json()
  const url = meta?.gltf?.url
  if (!url) throw new Error('No glTF download URL in Sketchfab response')

  console.log('Downloading glTF archive…')
  const zipRes = await fetch(url)
  if (!zipRes.ok) throw new Error(`Zip download failed (${zipRes.status})`)
  const buf = Buffer.from(await zipRes.arrayBuffer())
  writeFileSync(ZIP_PATH, buf)
  console.log(`Saved ${ZIP_PATH} (${(buf.length / 1e6).toFixed(1)} MB)`)

  try {
    execFileSync(
      'powershell',
      [
        '-NoProfile',
        '-Command',
        `Expand-Archive -LiteralPath '${ZIP_PATH}' -DestinationPath '${OUT_DIR}' -Force`,
      ],
      { stdio: 'inherit' },
    )
  } catch {
    execFileSync('tar', ['-xf', ZIP_PATH, '-C', OUT_DIR], { stdio: 'inherit' })
  }

  const found = findModelFile(OUT_DIR)
  if (!found) throw new Error('No .gltf/.glb found inside the Sketchfab zip')

  const publicUrl = '/' + relative(join(ROOT, 'public'), found).replaceAll('\\', '/')
  writeFileSync(
    URL_MODULE,
    `/** Auto-generated by scripts/download-seal5.mjs — do not edit by hand. */\nexport const SEAL5_MODEL_URL = '${publicUrl}'\n`,
  )

  writeFileSync(
    join(OUT_DIR, 'ATTRIBUTION.txt'),
    `2025 BYD Seal 5 DM-i (Chazor King Destroyer 05)
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
Source: https://sketchfab.com/3d-models/2025-byd-seal-5-dm-i-chazor-king-destroyer-05-${UID}
License: CC BY-NC-SA 4.0 — https://creativecommons.org/licenses/by-nc-sa/4.0/
Non-commercial use only. Attribution required. ShareAlike for derivatives.
Entry: ${publicUrl}
`,
  )

  console.log(`Model entry: ${publicUrl}`)
  console.log('Wrote src/three/modelUrl.ts')
  console.log('Refresh the app — the Seal 5 should load.')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
